### ISSUE TITLE
Difference between PCF8575 and PCF8575C.

### ISSUE THREAD

**Issue by water5** [mcauser/micropython-pcf8575#2]
The current code is match PCF8575 (use Push-pull output), 
[https://www.ti.com/lit/ds/symlink/pcf8575.pdf](https://www.ti.com/lit/ds/symlink/pcf8575.pdf)
page 13.

I test a PCF8575C (actually I use NXP PCF8575TS, I guess homologous PCF8575C? I'm not ensure, I can't find it's datasheet), it use Open-Drain output, 
[https://www.ti.com/lit/ds/symlink/pcf8575c.pdf](https://www.ti.com/lit/ds/symlink/pcf8575c.pdf)
page 12.
When use sourcing current method, must wire a pull-up resistor.

Is it have some difference except above require modify the code? if possible, please test.

**Comment by mcauser** [comment]
Hi, I don't own a `PCF8575C` or `PCF8575TS`.
Happy to review and merge any pull requests if you add support for the chips.
